version: '3'

services:
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./webauthn-html:/usr/share/nginx/html
    ports:
      - 80:80
    networks:
      mynet:

networks:
  mynet:
    driver: bridge